### ISSUE TITLE
SyntaxWarning on line 63 of utils.py in Python 3.12

### ISSUE THREAD

**Issue by gwachob** [vishalanandl177/DRF-API-Logger#94] opened 2024-03-18 06:32 UTC
Seeing an warning on our django deployment:

 `drf_api_logger/utils.py:63: SyntaxWarning: invalid escape sequence '\g`
 
 I believe the string that includes the \g escape just needs to be an r-string (e.g. `r'\g<1>***FILTERED***\g<3>'`) to remove this warning.
 
 I believe this is due to a new Python 3.12 feature - second bullet point of https://docs.python.org/dev/whatsnew/3.12.html#other-language-changes  - which also indicates this will become a SyntaxError in the future:
 
 

> A backslash-character pair that is not a valid escape sequence now generates a [SyntaxWarning](https://docs.python.org/dev/library/exceptions.html#SyntaxWarning), instead of [DeprecationWarning](https://docs.python.org/dev/library/exceptions.html#DeprecationWarning). For example, re.compile("\d+\.\d+") now emits a [SyntaxWarning](https://docs.python.org/dev/library/exceptions.html#SyntaxWarning) ("\d" is an invalid escape sequence, use raw strings for regular expression: re.compile(r"\d+\.\d+")). In a future Python version, [SyntaxError](https://docs.python.org/dev/library/exceptions.html#SyntaxError) will eventually be raised, instead of [SyntaxWarning](https://docs.python.org/dev/library/exceptions.html#SyntaxWarning). (Contributed by Victor Stinner in [gh-98401](https://github.com/python/cpython/issues/98401).)

**Comment by vishalanandl177** [comment] 2024-03-18 17:47
The issue is now fixed, it will be part of the next release.

**Closed by vishalanandl177** 2024-03-18 17:47 UTC
